### ISSUE TITLE
API section on componentjs.com

### ISSUE THREAD

**Issue by AuspeXeu** [rse/componentjs#40]
It would be amazing if you get directly to the relevant document when clicking on the images above the download buttons on this website http://componentjs.com/api.html instead of having a fullscreen sized image.

**Comment by JochenHoertreiter** [comment]
Agreed. It is frustrating each time you click on the images and just getting a bigger view of the image :)

**Comment by rse** [comment]
Now fixed. The images now also link directly to the HTML and PDF versions of the API.
